### ISSUE TITLE
Missing nullpointer check

### ISSUE THREAD

**Issue by chcg** [p0358/notepadpp-CodeStats#2]
@p0358 Happens at:

```
>	CodeStats.dll!CodeStats.CodeStatsPackage.ProcessPulses() Zeile 320	C#	Symbole wurden geladen.
 	CodeStats.dll!CodeStats.CodeStatsPackage.PluginCleanUp() Zeile 692	C#	Symbole wurden geladen.
 	CodeStats.dll!CodeStats.UnmanagedExports.beNotified(System.IntPtr notifyCode) Zeile 58	C#	Symbole wurden geladen.
```

> Ausnahme ausgelöst: "System.NullReferenceException" in CodeStats.dll
> Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

with:

```
		currentPulse	null	CodeStats.Pulse
+		pulseQueue	Count = 0	System.Collections.Concurrent.ConcurrentQueue<CodeStats.Pulse>
		pulseQueue.IsEmpty	true	bool
```

Also happening for x64. Startup N++, wait for the popup of CodeStats requesting the API key and close N++ without closing the popup.

-> missing nullpointer check at:

https://github.com/p0358/notepadpp-CodeStats/blob/master/CodeStats/CodeStatsPackage.cs#L320
 
for currentPulse

**Comment by chcg** [comment]
@p0358 Think this one could be closed with https://github.com/p0358/notepadpp-CodeStats/commit/ba4b9379a4872ed7797321925c76fe2dc28505c8

**Comment by p0358** [comment]
@chcg As far as I remember there were still some issues, I'll have to test it more thoroughly when I have a bit more time and then release a version.
