### ISSUE TITLE
Cannot connect to remote server

### ISSUE THREAD

**Issue by Aaron2550** [p0358/notepadpp-CodeStats#20]
Using version 1.0.1 from the [releases page](https://github.com/p0358/notepadpp-CodeStats/releases) i get the following error when trying to set up the codestats plugin:

[Screenshot](https://stronghold.host/media/8Xe2vHzE.png) (german text, sry :P)
roughly translated it means something along the lines of "Could not establish a connection to the remote server".
i have no third party firewall, [its not in my pi-hole block lists](https://stronghold.host/media/leKtTZPA.png), and the windows firewall is disabled.

im using win10 enterprise x64, version 1909, build 18363.815

(ive translated this one line for yall because im pretty sure its the most important one)
`[Code::Stats HandledException 10:00:05 ] Error Initializing CodeStats: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 141.8.224.221:443`
roughly means:
`[Code::Stats HandledException 10:00:05 ] Error Initializing CodeStats: System.Net.WebException: The connection to the remote server could not be established. ---> System.Net.Sockets.SocketException: the connection could not be established because the remote computer refused the connection 141.8.224.221:443`
[CodeStats.log](https://github.com/p0358/notepadpp-CodeStats/files/4554335/CodeStats.log)
which sounds like a ssl problem, given the port 443

**Comment by Nicd** [comment]
That is not the codestats.net IP address, which is `95.216.154.212`. Can you access codestats.net in your browser? The IP you are trying to connect to seems to belong to Rook Media GmbH, does that ring any bells?

BTW those images you linked are not opening for me.

**Comment by Aaron2550** [comment]
i have no idea who 141.8.224.221 is, when i open that ip in chrome it gets blocked by ublock origin, when i disable ublock i get forwarded to http://ww8.fwdservice.com/ which is one of these "buy this site now"-sites... 

yes, i can access codestats.net in my browser.

about the images: are you getting any errors or something because for me theyre loading...?

**Comment by Aaron2550** [comment]
![le_error](https://user-images.githubusercontent.com/24834067/80695220-e0a81380-8ad5-11ea-8fd8-59141575c233.png)
![pihole](https://user-images.githubusercontent.com/24834067/80695222-e140aa00-8ad5-11ea-9f98-e185d8592d5c.png)

**Comment by Nicd** [comment]
The images loaded now.

I'm not sure why your request is going to that IP. It seems there is something intercepting your request on your computer or with your ISP, or rewriting the DNS. Though I'm not sure why it works in the browser then. @p0358 do you have any idea what could be doing this?

**Comment by Aaron2550** [comment]
AV scan is clear, my DNS is set to 8.8.8.8 (secondary is my ISP's default)
heres a diagnostic traceroute my router gives me (incase that helps):
```
traceroute to 95.216.154.212 (95.216.154.212), 30 hops max, 38 byte packets
 1  10.178.192.1  4.469 ms
 2  172.17.162.89  6.914 ms
 3  80.64.181.67  5.647 ms
 4  *
 5  *
 6  213.239.252.218  42.444 ms
 7  213.239.252.101  46.280 ms
 8  88.198.245.254  46.162 ms
 9  *
10  95.216.129.70  47.371 ms
11  *
12  *
13  *
14  *
15  *
16  *
17  *
18  *
19  *
20  *
21  *
22  *
23  *
24  *
25  *
26  *
27  *
28  *
29  *
30  *
```

**Comment by Nicd** [comment]
This is due to the built release referring to old domain p0358.cf when it collects usage statistics. That domain has been taken over and points to that IP nowadays. The commit to change it was 37b28536febbabb7b3717b5ba454123bdc45e16a but there has not been a release that contains that commit.

The privacy and security implications are that the data in the statistics call (can be seen at https://github.com/p0358/notepadpp-CodeStats/commit/37b28536febbabb7b3717b5ba454123bdc45e16a#diff-bfde68f860e71f872afe9140ab75eafeL599-R632) are sent to this IP, but it seems the remote server is rejecting the connection. The Code::Stats API calls are sent to the correct server. But it would be best to get a new release to fix this.

**Comment by p0358** [comment]
> But it would be best to get a new release to fix this.

Hopefully I can release something finally this week. It would be an update that would fix numerous issues...

**Comment by Aaron2550** [comment]
thonks guys

**Comment by andyg2** [comment]
I had the same problem until I unchecked anonymous usage stats reporting. Then it started working.

![image](https://user-images.githubusercontent.com/1462766/107856140-2bc2c580-6e61-11eb-9902-9591fe7e31cb.png)
