### ISSUE TITLE
Question: what is the correct API URL in plugin settings?

### ISSUE THREAD

**Issue by AdamJel** [p0358/notepadpp-CodeStats#21]
Hi, I cannot figure out, what address should be in the API URL settings of the plug-in. I already tried these:
- https://codestats.net/api/my/pulses (default)
- https://codestats.net/api/ (from vscode)

In neither case the plug-in works, or maybe the plug-in does, but the pulse never reaches the api. In the end, it does not work.

Thanks for advice.

**Comment by lukasaldersley** [comment]
As far as I know the currently available version is broken. There is a version compiled by danijcom (see https://github.com/p0358/notepadpp-CodeStats/issues/17#issuecomment-565801382). That version does work, however when you close Notepad++ without having changed anything in any open file you will get a "Access violation" error (though it still works).

**Comment by p0358** [comment]
It used to be `https://codestats.net/api/my/pulses`, but I decided to change it to `https://codestats.net/api/` as of latest version released today for consistency, and in case we'd need to use more endpoints in the future. Backwards compatibility is preserved by detecting if the user-selected settings ends with `my/pulses` already.
