### ISSUE TITLE
So can you PLEASE rebuild it!

### ISSUE THREAD

**Issue by Kruemmelspalter** [p0358/notepadpp-CodeStats#22]
In #20 @p0358 said:
> > But it would be best to get a new release to fix this.
> 
> Hopefully I can release something finally this week. It would be an update that would fix numerous issues...

So can you please do that! I also have the issue from #20 and I don't know how to fix it (if I can fix it)

**Comment by lukasaldersley** [comment]
I have cretaed a slightly feature reduced version forked from this that does work. you can find it [here](https://github.com/lukasaldersley/notepadpp-CodeStats/releases). I plan on eventually adding back the features but htat might be a while.

**Comment by laerhu** [comment]
> I have cretaed a slightly feature reduced version forked from this that does work. you can find it [here](https://github.com/lukasaldersley/notepadpp-CodeStats/releases). I plan on eventually adding back the features but htat might be a while.

Could you build a 64 bit version? Thanks.

**Comment by lukasaldersley** [comment]
> > I have cretaed a slightly feature reduced version forked from this that does work. you can find it [here](https://github.com/lukasaldersley/notepadpp-CodeStats/releases). I plan on eventually adding back the features but htat might be a while.
> 
> Could you build a 64 bit version? Thanks.

Sure thing. I didn't test on 64 bit so I was unaware it didn't work. I apparently also updated the way preferences are stored back in December and forgot to publish updated binaries.
Anyway I updated the files (still available at the link above) and added an x64 version.
If there are problems let me know.

**Comment by laerhu** [comment]
> > > I have cretaed a slightly feature reduced version forked from this that does work. you can find it [here](https://github.com/lukasaldersley/notepadpp-CodeStats/releases). I plan on eventually adding back the features but htat might be a while.
> > 
> > 
> > Could you build a 64 bit version? Thanks.
> 
> Sure thing. I didn't test on 64 bit so I was unaware it didn't work. I apparently also updated the way preferences are stored back in December and forgot to publish updated binaries. Anyway I updated the files (still available at the link above) and added an x64 version. If there are problems let me know.

It works well on npp.8.4.4.portable.x64. Thank you very much. You are so fast.

**Comment by p0358** [comment]
Done, new version was released. Really sorry this took so long, especially that the version in the git was already working for more than 3 years...

Note that the latest version is in the Releases section on the repo, it's not yet in Notepad++ Plugins Admin!

Before that happens:
1. This update PR needs to be merged: https://github.com/notepad-plus-plus/nppPluginList/pull/514
2. Next Notepad++ update needs to be released as the plugin list is afaik still hardcoded there

Until then you need to manually download and unpack the latest plugin DLL.

Sorry again it took this obnoxious amount of time 🤦

**Comment by meechew** [comment]
I do not know what it takes for the NPP plug-in list to be updated, for the interim, Looks like a manual update is working. Thank you.
