### ISSUE TITLE
The remote name could not be resolved: "p0358.cf"

### ISSUE THREAD

**Issue by ireece1** [p0358/notepadpp-CodeStats#27]
I installed the plugin using the plugin admin and when I went to accept it i get the message:

The remote name could not be resolved: "p0358.cf"

**Comment by p0358** [comment]
That means you've installed an outdated version of the plugin. Make sure to update Notepad++, as the plugin list on Plugin Admin is frozen in time from when the particular version of it was released (which kinda sucks, but there's nothing we can do about it).

Note that you can also download an up-to-date version from GitHub releases section here on this repo instead as well
