### ISSUE TITLE
CSV File missing from extension_mapping.json

### ISSUE THREAD

**Issue by dropcase** [p0358/notepadpp-CodeStats#3]
When trying to do a text replace in a large CSV, the log file is flooded with lines like this, one for each time a replacement happens:

    [Code::Stats Info 09:58:26 AM] Key = "csv" is not found.
    [Code::Stats Info 09:58:26 AM] Key = "csv" is not found.
    [Code::Stats Info 09:58:26 AM] Key = "csv" is not found.
    [Code::Stats Info 09:58:26 AM] Key = "csv" is not found.

Can csv be added to the extension_mapping.json?

Thanks.

**Comment by p0358** [comment]
I've added it, sorry for the delay (I had Visual Studio install broken). The log flood is already fixed in master, I'll need to release a new version soon which will resolve this as well. Thanks for creating the issue.
