### ISSUE TITLE
ColdFusion is detected as plain text

### ISSUE THREAD

**Issue by jpsul** [p0358/notepadpp-CodeStats#7]
Similar to issue #6 also Coldfusion files are detected as plain text only. Usually the file extensions for CF files are .cfm or .cfc.

**Comment by p0358** [comment]
Should it be added as simply "ColdFusion" or should there be distinction between the 2 file types? Sorry for late reply

**Comment by jpsul** [comment]
There is no need for distinction between file types on this scope. Both file types should be detected as ColdFusion source code files. Thanks for the response!
